spring.application.name=ExpenseTracker

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5433}/${PGDATABASE:expense_tracker}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:xinxin11}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true