spring.application.name=Expense Tracker

spring.datasource.url=jdbc:postgresql://localhost:5433/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=xinxin11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect